<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Action' => '',
  'Base Path' => '',
  'Confirm to delete this item:' => '',
  'Copy' => '',
  'Copy directory {dir}' => '',
  'Copy file {file}' => '',
  'Create' => '',
  'Create New Dir' => '',
  'Date' => '',
  'Delete' => '',
  'Delete directory {dir}' => '',
  'Delete file {file}' => '',
  'Destination' => '',
  'Directory' => '',
  'Enter the name for the new directory:' => '',
  'Enter the new destination and name:' => '',
  'Enter the new location:' => '',
  'Enter the new name:' => '',
  'File to delete' => '',
  'Icon' => '',
  'C' => 'C',
  'X' => 'X',
  'M' => 'M',
  'R' => 'R',
  'Item: ' => '',
  'Media Browser' => '',
  'Media Type' => '',
  'Move' => '',
  'Move directory {dir}' => '',
  'Move file {file} to another location' => '',
  'Name' => '',
  'New Dest. and Name' => '',
  'New Directory' => '',
  'New Name' => '',
  'Old Name' => '',
  'Parameter 1' => '',
  'Path' => '',
  'Rename' => '',
  'Rename directory {dir}' => '',
  'Rename file {file}' => '',
  'Select a file to be uploaded:' => '',
  'Size' => '',
  'The directory <em>{p1}</em> has been created.' => '',
  'The file <em>{oldName}</em> has been uploaded as <em>{name}</em>.' => '',
  'The {mediaType} <em>{name}</em> has been copied to <em>{p1}</em>.' => '',
  'The {mediaType} <em>{name}</em> has been deleted.' => '',
  'The {mediaType} <em>{name}</em> has been moved to <em>{path}/{p1}</em>.' => '',
  'The {mediaType} <em>{name}</em> has been renamed to <em>{p1}</em>.' => '',
  'Type' => '',
  'Upload' => '',
  'Upload File' => '',
  'directory' => '',
  'file' => '',
);
